version: '3.4'

services:
  nginx:
    container_name: test_nginx
    image: nginx:1.20.0
    
  elasticsearch:
    container_name: test_elasticsearch
    image: elasticsearch:7.12.1

  kibana:
    container_name: test_kibana
    image: kibana:7.12.1

  redis:
    container_name: test_redis
    image: redis:6.2

  mongo:
    container_name: test_mongo
    image: mongo:4.4.6

  identityserver:
    container_name: test_identityserver
    image: test_identityserver:${TAG:-latest}
    build:
      context: .
      dockerfile: IdentityServer/Dockerfile
    depends_on:
      - nginx
      - elasticsearch
      - kibana
      - redis
      - mongo

  webapitest:
    container_name: test_webapitest
    image: test_webapitest:${TAG:-latest}
    build:
      context: .
      dockerfile: WebApiTest/Dockerfile
    depends_on:
      - identityserver

  webapitest2:
    container_name: test_webapitest2
    image: test_webapitest2:${TAG:-latest}
    build:
      context: .
      dockerfile: WebApiTest2/Dockerfile
    depends_on:
      - identityserver
      
