version: '3.4'

services:
  nginx:
    container_name: test_nginx
    image: nginx:1.20.0

  redis:
    container_name: test_redis
    image: redis:6.2

  identityserver:
    container_name: test_identityserver
    image: test_identityserver:${TAG:-latest}
    build:
      context: .
      dockerfile: IdentityServer/Dockerfile
    depends_on:
      - nginx
      - redis

  webapitest:
    container_name: test_webapitest
    image: test_webapitest:${TAG:-latest}
    build:
      context: .
      dockerfile: WebApiTest/Dockerfile
    depends_on:
      - identityserver

  webapitest2:
    container_name: test_webapitest2
    image: test_webapitest2:${TAG:-latest}
    build:
      context: .
      dockerfile: WebApiTest2/Dockerfile
    depends_on:
      - identityserver
      
