apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: rabbitmq-deployment
  labels:
    deployment: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      component: rabbitmq
  template:
    metadata:
      labels:
        component: rabbitmq
    spec:
      containers:
      - name: k8s-rabbitmq
        image: rabbitmq:3.8.16-management
        envFrom:
        - configMapRef:
            name: system-config
        - configMapRef:
            name: middleware-config
        securityContext:
          privileged: true
        ports:
        - containerPort: 5672
        - containerPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    service: rabbitmq
spec:
  type: ClusterIP
  selector:
    component: rabbitmq
  ports:
  - name: internal
    port: 80
    targetPort: 5672
  - name: web
    port: 8080
    targetPort: 15672