apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: zookeeper-deployment
  labels:
    deployment: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      component: zookeeper
  template:
    metadata:
      labels:
        component: zookeeper
    spec:
      containers:
      - name: k8s-zookeeper
        image: zookeeper:3.7.0
        envFrom:
        - configMapRef:
            name: system-config
        - configMapRef:
            name: middleware-config
        ports:
        - containerPort: 2181
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    service: zookeeper
spec:
  type: ClusterIP
  selector:
    component: zookeeper
  ports:
  - name: internal
    port: 80
    targetPort: 2181
  - name: web
    port: 8080
    targetPort: 8080